// Uploads tools/art/*.png to the forum through the logged-in Playwright profile (same profile as play.mjs)
// and writes lib/ui/assets.js with the resulting upload URLs. Re-run after changing tools/art-render.mjs.
import { chromium } from "playwright-core";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const PROFILE = (process.env.LOCALAPPDATA ?? "/tmp") + "/Temp/claude/wendao-browser-profile";
const SITE = "https://www.nodeloc.com";
const ctx = await chromium.launchPersistentContext(PROFILE, { channel: "chrome", headless: true });
const page = ctx.pages()[0] ?? (await ctx.newPage());
await page.goto(SITE + "/latest", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(1500);
let assets = {};
try { assets = { ...(await import("../lib/ui/assets.js")).ASSETS }; } catch {}
for (const f of readdirSync("tools/art").filter((x) => x.endsWith(".png"))) {
  const key = f.replace(/\.png$/, "");
  const only = process.argv[2] ? new RegExp(process.argv[2]) : null;
  if (only ? !only.test(key) : assets[key]) continue;
  const b64 = readFileSync("tools/art/" + f).toString("base64");
  let res;
  for (let attempt = 0; attempt < 6; attempt++) {
  res = await page.evaluate(async ({ b64, name }) => {
    const csrf = document.querySelector('meta[name="csrf-token"]')?.content;
    const bin = atob(b64); const arr = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
    const fd = new FormData(); fd.append("type", "composer"); fd.append("synchronous", "true"); fd.append("files[]", new File([arr], name, { type: "image/png" }));
    const r = await fetch("/uploads.json?client_id=wendao-art", { method: "POST", body: fd, headers: { "X-CSRF-Token": csrf, "X-Requested-With": "XMLHttpRequest" }, credentials: "include" });
    const text = await r.text();
    try { return { status: r.status, json: JSON.parse(text) }; } catch { return { status: r.status, text: text.slice(0, 200) }; }
  }, { b64, name: "wendao-" + f });
  if (res.status !== 429) break;
  const wait = (res.json?.extras?.wait_seconds ?? 30) + 2; console.log("rate limited, waiting", wait, "s"); await page.waitForTimeout(wait * 1000);
  }
  const url = res.json?.url;
  if (!url) { console.log("FAILED", f, res.status, JSON.stringify(res.json ?? res.text).slice(0, 300)); continue; }
  assets[key] = url.startsWith("//") ? "https:" + url : url.startsWith("/") ? SITE + url : url;
  console.log(key, assets[key]);
}
await ctx.close();
if (Object.keys(assets).length) {
  writeFileSync("lib/ui/assets.js", "// GENERATED by tools/art-upload.mjs — forum upload URLs for the blocks-surface art.\nexport const ASSETS = " + JSON.stringify(assets, null, 2) + ";\n");
  console.log("wrote lib/ui/assets.js with", Object.keys(assets).length, "assets");
}
