// Flatten lib/main.js and its relative imports (a DAG) into one module at src/main.js.
// The platform CLI inlines only a tree; diamond imports are the norm here, so we do it ourselves.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { strip } from "./strip.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = path.join(ROOT, "lib", "main.js");
const OUT = path.join(ROOT, "src", "main.js");
const IMPORT_RE = /^\s*import\s+(?:[^;'"]*?\sfrom\s+)?["'](\.[^"']+)["'];?\s*$/gm;
const DECL_RE = /^(?:export\s+)?(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z_$][\w$]*)/gm;

const order = [];
const seen = new Set();
async function visit(file, stack = []) {
  const abs = path.resolve(file);
  if (seen.has(abs)) return;
  if (stack.includes(abs)) throw new Error(`Circular import: ${[...stack, abs].map((f) => path.relative(ROOT, f)).join(" -> ")}`);
  const src = await readFile(abs, "utf8");
  for (const m of src.matchAll(IMPORT_RE)) {
    const target = path.resolve(path.dirname(abs), m[1]);
    await visit(target.endsWith(".js") ? target : `${target}.js`, [...stack, abs]);
  }
  seen.add(abs);
  order.push({ abs, src });
}
await visit(ENTRY);

const declared = new Map();
const parts = [];
for (const { abs, src } of order) {
  const rel = path.relative(ROOT, abs).split(path.sep).join("/");
  const isEntry = abs === path.resolve(ENTRY);
  // ignore declarations that live inside template literals (the webview client source)
  const scan = src.replace(/`[\s\S]*?`/g, "``");
  for (const m of scan.matchAll(DECL_RE)) {
    const name = m[1];
    if (declared.has(name)) throw new Error(`Duplicate top-level name "${name}" in ${rel} (also in ${declared.get(name)})`);
    declared.set(name, rel);
  }
  let body = src.replace(IMPORT_RE, "");
  if (!isEntry) body = body.replace(/^export\s+(?=(?:async\s+)?(?:function|const|let|var|class)\s)/gm, "");
  else body = body.replace(/^export\s+(?=(?:const|let|var|class)\s)/gm, "");
  parts.push(`// ---- ${rel}` + String.fromCharCode(10) + strip(body).trim() + String.fromCharCode(10));
}
const out = `// GENERATED by tools/build.mjs — edit lib/ instead.\n${parts.join("\n")}`;
await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, out, "utf8");
const bytes = Buffer.byteLength(out, "utf8");
console.log(`bundled ${order.length} modules -> ${path.relative(ROOT, OUT)} (${(bytes / 1024).toFixed(1)} KB)`);
if (bytes > 512 * 1024) { console.error("bundle exceeds 512 KB"); process.exit(1); }
